package com.cying.webtoolkit.model.authentication;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_no
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    private String roleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.desc
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_no
     *
     * @return the value of role.role_no
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_no
     *
     * @param roleNo the value for role.role_no
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo == null ? null : roleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.desc
     *
     * @return the value of role.desc
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.desc
     *
     * @param desc the value for role.desc
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}