package com.cying.webtoolkit.model.authentication;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_no
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_no
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    private String roleNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.user_no
     *
     * @return the value of user_role.user_no
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.user_no
     *
     * @param userNo the value for user_role.user_no
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_no
     *
     * @return the value of user_role.role_no
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_no
     *
     * @param roleNo the value for user_role.role_no
     *
     * @mbggenerated Sat May 14 17:51:54 CST 2016
     */
    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo == null ? null : roleNo.trim();
    }
}